---
title: Colloidsorg
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
kramdown:
  input: GFM
  default_lang: python
baseurl: "/colloidsorg"
plugins:
- jekyll-feed
